CREATE GENERATOR GEN_PESSOA_ID;

CREATE TABLE PESSOA (
    IDDONO  INTEGER NOT NULL,
    NOME    VARCHAR(100)
);

ALTER TABLE PESSOA ADD CONSTRAINT PK_PESSOA PRIMARY KEY (IDDONO);


CREATE TRIGGER PESSOA_BI FOR PESSOA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.iddono is null) then
    new.iddono = gen_id(gen_pessoa_id,1);
end

CREATE GENERATOR GEN_CAO_ID;

CREATE TABLE CAO (
    IDCAO  INTEGER NOT NULL,
    NOME   VARCHAR(50),
    RACA   VARCHAR(50)
);

ALTER TABLE CAO ADD CONSTRAINT PK_CAO PRIMARY KEY (IDCAO);


CREATE TRIGGER CAO_BI FOR CAO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idcao is null) then
    new.idcao = gen_id(gen_cao_id,1);
end

CREATE TABLE CAO_PESSOA (
    IDDONO  INTEGER NOT NULL,
    IDCAO   INTEGER NOT NULL
);

ALTER TABLE CAO_PESSOA ADD CONSTRAINT PK_CAO_PESSOA PRIMARY KEY (IDDONO, IDCAO);

ALTER TABLE CAO_PESSOA ADD CONSTRAINT FK_CAO FOREIGN KEY (IDCAO) REFERENCES CAO (IDCAO) ON DELETE CASCADE;
ALTER TABLE CAO_PESSOA ADD CONSTRAINT FK_DONO FOREIGN KEY (IDDONO) REFERENCES PESSOA (IDDONO) ON DELETE CASCADE;

